// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messeji.proto

package com.hello.messeji.api;

public final class Messeji {
  private Messeji() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReadReceiptOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReadReceipt)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int64 messageIds = 1;</code>
     */
    java.util.List<java.lang.Long> getMessageIdsList();
    /**
     * <code>repeated int64 messageIds = 1;</code>
     */
    int getMessageIdsCount();
    /**
     * <code>repeated int64 messageIds = 1;</code>
     */
    long getMessageIds(int index);
  }
  /**
   * Protobuf type {@code ReadReceipt}
   */
  public static final class ReadReceipt extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ReadReceipt)
      ReadReceiptOrBuilder {
    // Use ReadReceipt.newBuilder() to construct.
    private ReadReceipt(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReadReceipt(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReadReceipt defaultInstance;
    public static ReadReceipt getDefaultInstance() {
      return defaultInstance;
    }

    public ReadReceipt getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReadReceipt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                messageIds_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              messageIds_.add(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                messageIds_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                messageIds_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          messageIds_ = java.util.Collections.unmodifiableList(messageIds_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hello.messeji.api.Messeji.internal_static_ReadReceipt_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hello.messeji.api.Messeji.internal_static_ReadReceipt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hello.messeji.api.Messeji.ReadReceipt.class, com.hello.messeji.api.Messeji.ReadReceipt.Builder.class);
    }

    public static com.google.protobuf.Parser<ReadReceipt> PARSER =
        new com.google.protobuf.AbstractParser<ReadReceipt>() {
      public ReadReceipt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReadReceipt(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReadReceipt> getParserForType() {
      return PARSER;
    }

    public static final int MESSAGEIDS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> messageIds_;
    /**
     * <code>repeated int64 messageIds = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getMessageIdsList() {
      return messageIds_;
    }
    /**
     * <code>repeated int64 messageIds = 1;</code>
     */
    public int getMessageIdsCount() {
      return messageIds_.size();
    }
    /**
     * <code>repeated int64 messageIds = 1;</code>
     */
    public long getMessageIds(int index) {
      return messageIds_.get(index);
    }

    private void initFields() {
      messageIds_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < messageIds_.size(); i++) {
        output.writeInt64(1, messageIds_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < messageIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(messageIds_.get(i));
        }
        size += dataSize;
        size += 1 * getMessageIdsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hello.messeji.api.Messeji.ReadReceipt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.messeji.api.Messeji.ReadReceipt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.messeji.api.Messeji.ReadReceipt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.messeji.api.Messeji.ReadReceipt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.messeji.api.Messeji.ReadReceipt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.messeji.api.Messeji.ReadReceipt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hello.messeji.api.Messeji.ReadReceipt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hello.messeji.api.Messeji.ReadReceipt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hello.messeji.api.Messeji.ReadReceipt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.messeji.api.Messeji.ReadReceipt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hello.messeji.api.Messeji.ReadReceipt prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReadReceipt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReadReceipt)
        com.hello.messeji.api.Messeji.ReadReceiptOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hello.messeji.api.Messeji.internal_static_ReadReceipt_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hello.messeji.api.Messeji.internal_static_ReadReceipt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hello.messeji.api.Messeji.ReadReceipt.class, com.hello.messeji.api.Messeji.ReadReceipt.Builder.class);
      }

      // Construct using com.hello.messeji.api.Messeji.ReadReceipt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hello.messeji.api.Messeji.internal_static_ReadReceipt_descriptor;
      }

      public com.hello.messeji.api.Messeji.ReadReceipt getDefaultInstanceForType() {
        return com.hello.messeji.api.Messeji.ReadReceipt.getDefaultInstance();
      }

      public com.hello.messeji.api.Messeji.ReadReceipt build() {
        com.hello.messeji.api.Messeji.ReadReceipt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hello.messeji.api.Messeji.ReadReceipt buildPartial() {
        com.hello.messeji.api.Messeji.ReadReceipt result = new com.hello.messeji.api.Messeji.ReadReceipt(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          messageIds_ = java.util.Collections.unmodifiableList(messageIds_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.messageIds_ = messageIds_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hello.messeji.api.Messeji.ReadReceipt) {
          return mergeFrom((com.hello.messeji.api.Messeji.ReadReceipt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hello.messeji.api.Messeji.ReadReceipt other) {
        if (other == com.hello.messeji.api.Messeji.ReadReceipt.getDefaultInstance()) return this;
        if (!other.messageIds_.isEmpty()) {
          if (messageIds_.isEmpty()) {
            messageIds_ = other.messageIds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMessageIdsIsMutable();
            messageIds_.addAll(other.messageIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hello.messeji.api.Messeji.ReadReceipt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hello.messeji.api.Messeji.ReadReceipt) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Long> messageIds_ = java.util.Collections.emptyList();
      private void ensureMessageIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          messageIds_ = new java.util.ArrayList<java.lang.Long>(messageIds_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int64 messageIds = 1;</code>
       */
      public java.util.List<java.lang.Long>
          getMessageIdsList() {
        return java.util.Collections.unmodifiableList(messageIds_);
      }
      /**
       * <code>repeated int64 messageIds = 1;</code>
       */
      public int getMessageIdsCount() {
        return messageIds_.size();
      }
      /**
       * <code>repeated int64 messageIds = 1;</code>
       */
      public long getMessageIds(int index) {
        return messageIds_.get(index);
      }
      /**
       * <code>repeated int64 messageIds = 1;</code>
       */
      public Builder setMessageIds(
          int index, long value) {
        ensureMessageIdsIsMutable();
        messageIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 messageIds = 1;</code>
       */
      public Builder addMessageIds(long value) {
        ensureMessageIdsIsMutable();
        messageIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 messageIds = 1;</code>
       */
      public Builder addAllMessageIds(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureMessageIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messageIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 messageIds = 1;</code>
       */
      public Builder clearMessageIds() {
        messageIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ReadReceipt)
    }

    static {
      defaultInstance = new ReadReceipt(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ReadReceipt)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string senderId = 1;</code>
     *
     * <pre>
     * Unique ID associated with the sender, in order to disambiguate between multiple senders
     * each generating their own idea of an “order” (see below)
     * </pre>
     */
    boolean hasSenderId();
    /**
     * <code>optional string senderId = 1;</code>
     *
     * <pre>
     * Unique ID associated with the sender, in order to disambiguate between multiple senders
     * each generating their own idea of an “order” (see below)
     * </pre>
     */
    java.lang.String getSenderId();
    /**
     * <code>optional string senderId = 1;</code>
     *
     * <pre>
     * Unique ID associated with the sender, in order to disambiguate between multiple senders
     * each generating their own idea of an “order” (see below)
     * </pre>
     */
    com.google.protobuf.ByteString
        getSenderIdBytes();

    /**
     * <code>required int64 order = 2;</code>
     *
     * <pre>
     * The order as indicated by the sender. Usually this will be a timestamp.
     * The greater the order, the more recent the message.
     * </pre>
     */
    boolean hasOrder();
    /**
     * <code>required int64 order = 2;</code>
     *
     * <pre>
     * The order as indicated by the sender. Usually this will be a timestamp.
     * The greater the order, the more recent the message.
     * </pre>
     */
    long getOrder();

    /**
     * <code>optional int64 messageId = 3;</code>
     *
     * <pre>
     * Server-generated unique messageId for this message.
     * </pre>
     */
    boolean hasMessageId();
    /**
     * <code>optional int64 messageId = 3;</code>
     *
     * <pre>
     * Server-generated unique messageId for this message.
     * </pre>
     */
    long getMessageId();

    /**
     * <code>required .Message.Type type = 4;</code>
     *
     * <pre>
     * What kind of message this is.
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required .Message.Type type = 4;</code>
     *
     * <pre>
     * What kind of message this is.
     * </pre>
     */
    com.hello.messeji.api.Messeji.Message.Type getType();

    /**
     * <code>optional .SleepSoundsCommand sleepSoundsCommand = 5;</code>
     */
    boolean hasSleepSoundsCommand();
    /**
     * <code>optional .SleepSoundsCommand sleepSoundsCommand = 5;</code>
     */
    com.hello.messeji.api.SleepSounds.SleepSoundsCommand getSleepSoundsCommand();
    /**
     * <code>optional .SleepSoundsCommand sleepSoundsCommand = 5;</code>
     */
    com.hello.messeji.api.SleepSounds.SleepSoundsCommandOrBuilder getSleepSoundsCommandOrBuilder();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              senderId_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              order_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              messageId_ = input.readInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.hello.messeji.api.Messeji.Message.Type value = com.hello.messeji.api.Messeji.Message.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                type_ = value;
              }
              break;
            }
            case 42: {
              com.hello.messeji.api.SleepSounds.SleepSoundsCommand.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = sleepSoundsCommand_.toBuilder();
              }
              sleepSoundsCommand_ = input.readMessage(com.hello.messeji.api.SleepSounds.SleepSoundsCommand.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sleepSoundsCommand_);
                sleepSoundsCommand_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hello.messeji.api.Messeji.internal_static_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hello.messeji.api.Messeji.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hello.messeji.api.Messeji.Message.class, com.hello.messeji.api.Messeji.Message.Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Message.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SLEEP_SOUNDS = 1;</code>
       */
      SLEEP_SOUNDS(0, 1),
      ;

      /**
       * <code>SLEEP_SOUNDS = 1;</code>
       */
      public static final int SLEEP_SOUNDS_VALUE = 1;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return SLEEP_SOUNDS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.hello.messeji.api.Messeji.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Message.Type)
    }

    private int bitField0_;
    public static final int SENDERID_FIELD_NUMBER = 1;
    private java.lang.Object senderId_;
    /**
     * <code>optional string senderId = 1;</code>
     *
     * <pre>
     * Unique ID associated with the sender, in order to disambiguate between multiple senders
     * each generating their own idea of an “order” (see below)
     * </pre>
     */
    public boolean hasSenderId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string senderId = 1;</code>
     *
     * <pre>
     * Unique ID associated with the sender, in order to disambiguate between multiple senders
     * each generating their own idea of an “order” (see below)
     * </pre>
     */
    public java.lang.String getSenderId() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string senderId = 1;</code>
     *
     * <pre>
     * Unique ID associated with the sender, in order to disambiguate between multiple senders
     * each generating their own idea of an “order” (see below)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSenderIdBytes() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDER_FIELD_NUMBER = 2;
    private long order_;
    /**
     * <code>required int64 order = 2;</code>
     *
     * <pre>
     * The order as indicated by the sender. Usually this will be a timestamp.
     * The greater the order, the more recent the message.
     * </pre>
     */
    public boolean hasOrder() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 order = 2;</code>
     *
     * <pre>
     * The order as indicated by the sender. Usually this will be a timestamp.
     * The greater the order, the more recent the message.
     * </pre>
     */
    public long getOrder() {
      return order_;
    }

    public static final int MESSAGEID_FIELD_NUMBER = 3;
    private long messageId_;
    /**
     * <code>optional int64 messageId = 3;</code>
     *
     * <pre>
     * Server-generated unique messageId for this message.
     * </pre>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 messageId = 3;</code>
     *
     * <pre>
     * Server-generated unique messageId for this message.
     * </pre>
     */
    public long getMessageId() {
      return messageId_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private com.hello.messeji.api.Messeji.Message.Type type_;
    /**
     * <code>required .Message.Type type = 4;</code>
     *
     * <pre>
     * What kind of message this is.
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .Message.Type type = 4;</code>
     *
     * <pre>
     * What kind of message this is.
     * </pre>
     */
    public com.hello.messeji.api.Messeji.Message.Type getType() {
      return type_;
    }

    public static final int SLEEPSOUNDSCOMMAND_FIELD_NUMBER = 5;
    private com.hello.messeji.api.SleepSounds.SleepSoundsCommand sleepSoundsCommand_;
    /**
     * <code>optional .SleepSoundsCommand sleepSoundsCommand = 5;</code>
     */
    public boolean hasSleepSoundsCommand() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .SleepSoundsCommand sleepSoundsCommand = 5;</code>
     */
    public com.hello.messeji.api.SleepSounds.SleepSoundsCommand getSleepSoundsCommand() {
      return sleepSoundsCommand_;
    }
    /**
     * <code>optional .SleepSoundsCommand sleepSoundsCommand = 5;</code>
     */
    public com.hello.messeji.api.SleepSounds.SleepSoundsCommandOrBuilder getSleepSoundsCommandOrBuilder() {
      return sleepSoundsCommand_;
    }

    private void initFields() {
      senderId_ = "";
      order_ = 0L;
      messageId_ = 0L;
      type_ = com.hello.messeji.api.Messeji.Message.Type.SLEEP_SOUNDS;
      sleepSoundsCommand_ = com.hello.messeji.api.SleepSounds.SleepSoundsCommand.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOrder()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSenderIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, order_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, messageId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, type_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, sleepSoundsCommand_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSenderIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, order_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, messageId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, sleepSoundsCommand_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hello.messeji.api.Messeji.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.messeji.api.Messeji.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.messeji.api.Messeji.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.messeji.api.Messeji.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.messeji.api.Messeji.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.messeji.api.Messeji.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hello.messeji.api.Messeji.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hello.messeji.api.Messeji.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hello.messeji.api.Messeji.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.messeji.api.Messeji.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hello.messeji.api.Messeji.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        com.hello.messeji.api.Messeji.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hello.messeji.api.Messeji.internal_static_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hello.messeji.api.Messeji.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hello.messeji.api.Messeji.Message.class, com.hello.messeji.api.Messeji.Message.Builder.class);
      }

      // Construct using com.hello.messeji.api.Messeji.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSleepSoundsCommandFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        senderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        order_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        messageId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = com.hello.messeji.api.Messeji.Message.Type.SLEEP_SOUNDS;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (sleepSoundsCommandBuilder_ == null) {
          sleepSoundsCommand_ = com.hello.messeji.api.SleepSounds.SleepSoundsCommand.getDefaultInstance();
        } else {
          sleepSoundsCommandBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hello.messeji.api.Messeji.internal_static_Message_descriptor;
      }

      public com.hello.messeji.api.Messeji.Message getDefaultInstanceForType() {
        return com.hello.messeji.api.Messeji.Message.getDefaultInstance();
      }

      public com.hello.messeji.api.Messeji.Message build() {
        com.hello.messeji.api.Messeji.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hello.messeji.api.Messeji.Message buildPartial() {
        com.hello.messeji.api.Messeji.Message result = new com.hello.messeji.api.Messeji.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.senderId_ = senderId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.order_ = order_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (sleepSoundsCommandBuilder_ == null) {
          result.sleepSoundsCommand_ = sleepSoundsCommand_;
        } else {
          result.sleepSoundsCommand_ = sleepSoundsCommandBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hello.messeji.api.Messeji.Message) {
          return mergeFrom((com.hello.messeji.api.Messeji.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hello.messeji.api.Messeji.Message other) {
        if (other == com.hello.messeji.api.Messeji.Message.getDefaultInstance()) return this;
        if (other.hasSenderId()) {
          bitField0_ |= 0x00000001;
          senderId_ = other.senderId_;
          onChanged();
        }
        if (other.hasOrder()) {
          setOrder(other.getOrder());
        }
        if (other.hasMessageId()) {
          setMessageId(other.getMessageId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSleepSoundsCommand()) {
          mergeSleepSoundsCommand(other.getSleepSoundsCommand());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOrder()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hello.messeji.api.Messeji.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hello.messeji.api.Messeji.Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object senderId_ = "";
      /**
       * <code>optional string senderId = 1;</code>
       *
       * <pre>
       * Unique ID associated with the sender, in order to disambiguate between multiple senders
       * each generating their own idea of an “order” (see below)
       * </pre>
       */
      public boolean hasSenderId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string senderId = 1;</code>
       *
       * <pre>
       * Unique ID associated with the sender, in order to disambiguate between multiple senders
       * each generating their own idea of an “order” (see below)
       * </pre>
       */
      public java.lang.String getSenderId() {
        java.lang.Object ref = senderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            senderId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string senderId = 1;</code>
       *
       * <pre>
       * Unique ID associated with the sender, in order to disambiguate between multiple senders
       * each generating their own idea of an “order” (see below)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSenderIdBytes() {
        java.lang.Object ref = senderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string senderId = 1;</code>
       *
       * <pre>
       * Unique ID associated with the sender, in order to disambiguate between multiple senders
       * each generating their own idea of an “order” (see below)
       * </pre>
       */
      public Builder setSenderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        senderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string senderId = 1;</code>
       *
       * <pre>
       * Unique ID associated with the sender, in order to disambiguate between multiple senders
       * each generating their own idea of an “order” (see below)
       * </pre>
       */
      public Builder clearSenderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        senderId_ = getDefaultInstance().getSenderId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string senderId = 1;</code>
       *
       * <pre>
       * Unique ID associated with the sender, in order to disambiguate between multiple senders
       * each generating their own idea of an “order” (see below)
       * </pre>
       */
      public Builder setSenderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        senderId_ = value;
        onChanged();
        return this;
      }

      private long order_ ;
      /**
       * <code>required int64 order = 2;</code>
       *
       * <pre>
       * The order as indicated by the sender. Usually this will be a timestamp.
       * The greater the order, the more recent the message.
       * </pre>
       */
      public boolean hasOrder() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 order = 2;</code>
       *
       * <pre>
       * The order as indicated by the sender. Usually this will be a timestamp.
       * The greater the order, the more recent the message.
       * </pre>
       */
      public long getOrder() {
        return order_;
      }
      /**
       * <code>required int64 order = 2;</code>
       *
       * <pre>
       * The order as indicated by the sender. Usually this will be a timestamp.
       * The greater the order, the more recent the message.
       * </pre>
       */
      public Builder setOrder(long value) {
        bitField0_ |= 0x00000002;
        order_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 order = 2;</code>
       *
       * <pre>
       * The order as indicated by the sender. Usually this will be a timestamp.
       * The greater the order, the more recent the message.
       * </pre>
       */
      public Builder clearOrder() {
        bitField0_ = (bitField0_ & ~0x00000002);
        order_ = 0L;
        onChanged();
        return this;
      }

      private long messageId_ ;
      /**
       * <code>optional int64 messageId = 3;</code>
       *
       * <pre>
       * Server-generated unique messageId for this message.
       * </pre>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 messageId = 3;</code>
       *
       * <pre>
       * Server-generated unique messageId for this message.
       * </pre>
       */
      public long getMessageId() {
        return messageId_;
      }
      /**
       * <code>optional int64 messageId = 3;</code>
       *
       * <pre>
       * Server-generated unique messageId for this message.
       * </pre>
       */
      public Builder setMessageId(long value) {
        bitField0_ |= 0x00000004;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 messageId = 3;</code>
       *
       * <pre>
       * Server-generated unique messageId for this message.
       * </pre>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        messageId_ = 0L;
        onChanged();
        return this;
      }

      private com.hello.messeji.api.Messeji.Message.Type type_ = com.hello.messeji.api.Messeji.Message.Type.SLEEP_SOUNDS;
      /**
       * <code>required .Message.Type type = 4;</code>
       *
       * <pre>
       * What kind of message this is.
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .Message.Type type = 4;</code>
       *
       * <pre>
       * What kind of message this is.
       * </pre>
       */
      public com.hello.messeji.api.Messeji.Message.Type getType() {
        return type_;
      }
      /**
       * <code>required .Message.Type type = 4;</code>
       *
       * <pre>
       * What kind of message this is.
       * </pre>
       */
      public Builder setType(com.hello.messeji.api.Messeji.Message.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Message.Type type = 4;</code>
       *
       * <pre>
       * What kind of message this is.
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = com.hello.messeji.api.Messeji.Message.Type.SLEEP_SOUNDS;
        onChanged();
        return this;
      }

      private com.hello.messeji.api.SleepSounds.SleepSoundsCommand sleepSoundsCommand_ = com.hello.messeji.api.SleepSounds.SleepSoundsCommand.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.hello.messeji.api.SleepSounds.SleepSoundsCommand, com.hello.messeji.api.SleepSounds.SleepSoundsCommand.Builder, com.hello.messeji.api.SleepSounds.SleepSoundsCommandOrBuilder> sleepSoundsCommandBuilder_;
      /**
       * <code>optional .SleepSoundsCommand sleepSoundsCommand = 5;</code>
       */
      public boolean hasSleepSoundsCommand() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .SleepSoundsCommand sleepSoundsCommand = 5;</code>
       */
      public com.hello.messeji.api.SleepSounds.SleepSoundsCommand getSleepSoundsCommand() {
        if (sleepSoundsCommandBuilder_ == null) {
          return sleepSoundsCommand_;
        } else {
          return sleepSoundsCommandBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .SleepSoundsCommand sleepSoundsCommand = 5;</code>
       */
      public Builder setSleepSoundsCommand(com.hello.messeji.api.SleepSounds.SleepSoundsCommand value) {
        if (sleepSoundsCommandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sleepSoundsCommand_ = value;
          onChanged();
        } else {
          sleepSoundsCommandBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .SleepSoundsCommand sleepSoundsCommand = 5;</code>
       */
      public Builder setSleepSoundsCommand(
          com.hello.messeji.api.SleepSounds.SleepSoundsCommand.Builder builderForValue) {
        if (sleepSoundsCommandBuilder_ == null) {
          sleepSoundsCommand_ = builderForValue.build();
          onChanged();
        } else {
          sleepSoundsCommandBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .SleepSoundsCommand sleepSoundsCommand = 5;</code>
       */
      public Builder mergeSleepSoundsCommand(com.hello.messeji.api.SleepSounds.SleepSoundsCommand value) {
        if (sleepSoundsCommandBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              sleepSoundsCommand_ != com.hello.messeji.api.SleepSounds.SleepSoundsCommand.getDefaultInstance()) {
            sleepSoundsCommand_ =
              com.hello.messeji.api.SleepSounds.SleepSoundsCommand.newBuilder(sleepSoundsCommand_).mergeFrom(value).buildPartial();
          } else {
            sleepSoundsCommand_ = value;
          }
          onChanged();
        } else {
          sleepSoundsCommandBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .SleepSoundsCommand sleepSoundsCommand = 5;</code>
       */
      public Builder clearSleepSoundsCommand() {
        if (sleepSoundsCommandBuilder_ == null) {
          sleepSoundsCommand_ = com.hello.messeji.api.SleepSounds.SleepSoundsCommand.getDefaultInstance();
          onChanged();
        } else {
          sleepSoundsCommandBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .SleepSoundsCommand sleepSoundsCommand = 5;</code>
       */
      public com.hello.messeji.api.SleepSounds.SleepSoundsCommand.Builder getSleepSoundsCommandBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getSleepSoundsCommandFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SleepSoundsCommand sleepSoundsCommand = 5;</code>
       */
      public com.hello.messeji.api.SleepSounds.SleepSoundsCommandOrBuilder getSleepSoundsCommandOrBuilder() {
        if (sleepSoundsCommandBuilder_ != null) {
          return sleepSoundsCommandBuilder_.getMessageOrBuilder();
        } else {
          return sleepSoundsCommand_;
        }
      }
      /**
       * <code>optional .SleepSoundsCommand sleepSoundsCommand = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.hello.messeji.api.SleepSounds.SleepSoundsCommand, com.hello.messeji.api.SleepSounds.SleepSoundsCommand.Builder, com.hello.messeji.api.SleepSounds.SleepSoundsCommandOrBuilder> 
          getSleepSoundsCommandFieldBuilder() {
        if (sleepSoundsCommandBuilder_ == null) {
          sleepSoundsCommandBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.hello.messeji.api.SleepSounds.SleepSoundsCommand, com.hello.messeji.api.SleepSounds.SleepSoundsCommand.Builder, com.hello.messeji.api.SleepSounds.SleepSoundsCommandOrBuilder>(
                  getSleepSoundsCommand(),
                  getParentForChildren(),
                  isClean());
          sleepSoundsCommand_ = null;
        }
        return sleepSoundsCommandBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Message)
  }

  public interface MultiMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MultiMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Message messages = 1;</code>
     */
    java.util.List<com.hello.messeji.api.Messeji.Message> 
        getMessagesList();
    /**
     * <code>repeated .Message messages = 1;</code>
     */
    com.hello.messeji.api.Messeji.Message getMessages(int index);
    /**
     * <code>repeated .Message messages = 1;</code>
     */
    int getMessagesCount();
    /**
     * <code>repeated .Message messages = 1;</code>
     */
    java.util.List<? extends com.hello.messeji.api.Messeji.MessageOrBuilder> 
        getMessagesOrBuilderList();
    /**
     * <code>repeated .Message messages = 1;</code>
     */
    com.hello.messeji.api.Messeji.MessageOrBuilder getMessagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code MultiMessage}
   */
  public static final class MultiMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MultiMessage)
      MultiMessageOrBuilder {
    // Use MultiMessage.newBuilder() to construct.
    private MultiMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MultiMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MultiMessage defaultInstance;
    public static MultiMessage getDefaultInstance() {
      return defaultInstance;
    }

    public MultiMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MultiMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                messages_ = new java.util.ArrayList<com.hello.messeji.api.Messeji.Message>();
                mutable_bitField0_ |= 0x00000001;
              }
              messages_.add(input.readMessage(com.hello.messeji.api.Messeji.Message.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          messages_ = java.util.Collections.unmodifiableList(messages_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hello.messeji.api.Messeji.internal_static_MultiMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hello.messeji.api.Messeji.internal_static_MultiMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hello.messeji.api.Messeji.MultiMessage.class, com.hello.messeji.api.Messeji.MultiMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<MultiMessage> PARSER =
        new com.google.protobuf.AbstractParser<MultiMessage>() {
      public MultiMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MultiMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MultiMessage> getParserForType() {
      return PARSER;
    }

    public static final int MESSAGES_FIELD_NUMBER = 1;
    private java.util.List<com.hello.messeji.api.Messeji.Message> messages_;
    /**
     * <code>repeated .Message messages = 1;</code>
     */
    public java.util.List<com.hello.messeji.api.Messeji.Message> getMessagesList() {
      return messages_;
    }
    /**
     * <code>repeated .Message messages = 1;</code>
     */
    public java.util.List<? extends com.hello.messeji.api.Messeji.MessageOrBuilder> 
        getMessagesOrBuilderList() {
      return messages_;
    }
    /**
     * <code>repeated .Message messages = 1;</code>
     */
    public int getMessagesCount() {
      return messages_.size();
    }
    /**
     * <code>repeated .Message messages = 1;</code>
     */
    public com.hello.messeji.api.Messeji.Message getMessages(int index) {
      return messages_.get(index);
    }
    /**
     * <code>repeated .Message messages = 1;</code>
     */
    public com.hello.messeji.api.Messeji.MessageOrBuilder getMessagesOrBuilder(
        int index) {
      return messages_.get(index);
    }

    private void initFields() {
      messages_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getMessagesCount(); i++) {
        if (!getMessages(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < messages_.size(); i++) {
        output.writeMessage(1, messages_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < messages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, messages_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hello.messeji.api.Messeji.MultiMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.messeji.api.Messeji.MultiMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.messeji.api.Messeji.MultiMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.messeji.api.Messeji.MultiMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.messeji.api.Messeji.MultiMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.messeji.api.Messeji.MultiMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hello.messeji.api.Messeji.MultiMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hello.messeji.api.Messeji.MultiMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hello.messeji.api.Messeji.MultiMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.messeji.api.Messeji.MultiMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hello.messeji.api.Messeji.MultiMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MultiMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MultiMessage)
        com.hello.messeji.api.Messeji.MultiMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hello.messeji.api.Messeji.internal_static_MultiMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hello.messeji.api.Messeji.internal_static_MultiMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hello.messeji.api.Messeji.MultiMessage.class, com.hello.messeji.api.Messeji.MultiMessage.Builder.class);
      }

      // Construct using com.hello.messeji.api.Messeji.MultiMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMessagesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hello.messeji.api.Messeji.internal_static_MultiMessage_descriptor;
      }

      public com.hello.messeji.api.Messeji.MultiMessage getDefaultInstanceForType() {
        return com.hello.messeji.api.Messeji.MultiMessage.getDefaultInstance();
      }

      public com.hello.messeji.api.Messeji.MultiMessage build() {
        com.hello.messeji.api.Messeji.MultiMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hello.messeji.api.Messeji.MultiMessage buildPartial() {
        com.hello.messeji.api.Messeji.MultiMessage result = new com.hello.messeji.api.Messeji.MultiMessage(this);
        int from_bitField0_ = bitField0_;
        if (messagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            messages_ = java.util.Collections.unmodifiableList(messages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.messages_ = messages_;
        } else {
          result.messages_ = messagesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hello.messeji.api.Messeji.MultiMessage) {
          return mergeFrom((com.hello.messeji.api.Messeji.MultiMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hello.messeji.api.Messeji.MultiMessage other) {
        if (other == com.hello.messeji.api.Messeji.MultiMessage.getDefaultInstance()) return this;
        if (messagesBuilder_ == null) {
          if (!other.messages_.isEmpty()) {
            if (messages_.isEmpty()) {
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMessagesIsMutable();
              messages_.addAll(other.messages_);
            }
            onChanged();
          }
        } else {
          if (!other.messages_.isEmpty()) {
            if (messagesBuilder_.isEmpty()) {
              messagesBuilder_.dispose();
              messagesBuilder_ = null;
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              messagesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMessagesFieldBuilder() : null;
            } else {
              messagesBuilder_.addAllMessages(other.messages_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getMessagesCount(); i++) {
          if (!getMessages(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hello.messeji.api.Messeji.MultiMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hello.messeji.api.Messeji.MultiMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.hello.messeji.api.Messeji.Message> messages_ =
        java.util.Collections.emptyList();
      private void ensureMessagesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          messages_ = new java.util.ArrayList<com.hello.messeji.api.Messeji.Message>(messages_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.hello.messeji.api.Messeji.Message, com.hello.messeji.api.Messeji.Message.Builder, com.hello.messeji.api.Messeji.MessageOrBuilder> messagesBuilder_;

      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public java.util.List<com.hello.messeji.api.Messeji.Message> getMessagesList() {
        if (messagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(messages_);
        } else {
          return messagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public int getMessagesCount() {
        if (messagesBuilder_ == null) {
          return messages_.size();
        } else {
          return messagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public com.hello.messeji.api.Messeji.Message getMessages(int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);
        } else {
          return messagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public Builder setMessages(
          int index, com.hello.messeji.api.Messeji.Message value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.set(index, value);
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public Builder setMessages(
          int index, com.hello.messeji.api.Messeji.Message.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.set(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public Builder addMessages(com.hello.messeji.api.Messeji.Message value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public Builder addMessages(
          int index, com.hello.messeji.api.Messeji.Message value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(index, value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public Builder addMessages(
          com.hello.messeji.api.Messeji.Message.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public Builder addMessages(
          int index, com.hello.messeji.api.Messeji.Message.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public Builder addAllMessages(
          java.lang.Iterable<? extends com.hello.messeji.api.Messeji.Message> values) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, messages_);
          onChanged();
        } else {
          messagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public Builder clearMessages() {
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public Builder removeMessages(int index) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.remove(index);
          onChanged();
        } else {
          messagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public com.hello.messeji.api.Messeji.Message.Builder getMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public com.hello.messeji.api.Messeji.MessageOrBuilder getMessagesOrBuilder(
          int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);  } else {
          return messagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public java.util.List<? extends com.hello.messeji.api.Messeji.MessageOrBuilder> 
           getMessagesOrBuilderList() {
        if (messagesBuilder_ != null) {
          return messagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(messages_);
        }
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public com.hello.messeji.api.Messeji.Message.Builder addMessagesBuilder() {
        return getMessagesFieldBuilder().addBuilder(
            com.hello.messeji.api.Messeji.Message.getDefaultInstance());
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public com.hello.messeji.api.Messeji.Message.Builder addMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().addBuilder(
            index, com.hello.messeji.api.Messeji.Message.getDefaultInstance());
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public java.util.List<com.hello.messeji.api.Messeji.Message.Builder> 
           getMessagesBuilderList() {
        return getMessagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.hello.messeji.api.Messeji.Message, com.hello.messeji.api.Messeji.Message.Builder, com.hello.messeji.api.Messeji.MessageOrBuilder> 
          getMessagesFieldBuilder() {
        if (messagesBuilder_ == null) {
          messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.hello.messeji.api.Messeji.Message, com.hello.messeji.api.Messeji.Message.Builder, com.hello.messeji.api.Messeji.MessageOrBuilder>(
                  messages_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          messages_ = null;
        }
        return messagesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:MultiMessage)
    }

    static {
      defaultInstance = new MultiMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MultiMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReadReceipt_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReadReceipt_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MultiMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MultiMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmesseji.proto\032\022sleep_sounds.proto\"!\n\013R" +
      "eadReceipt\022\022\n\nmessageIds\030\001 \003(\003\"\245\001\n\007Messa" +
      "ge\022\020\n\010senderId\030\001 \001(\t\022\r\n\005order\030\002 \002(\003\022\021\n\tm" +
      "essageId\030\003 \001(\003\022\033\n\004type\030\004 \002(\0162\r.Message.T" +
      "ype\022/\n\022sleepSoundsCommand\030\005 \001(\0132\023.SleepS" +
      "oundsCommand\"\030\n\004Type\022\020\n\014SLEEP_SOUNDS\020\001\"*" +
      "\n\014MultiMessage\022\032\n\010messages\030\001 \003(\0132\010.Messa" +
      "geB\027\n\025com.hello.messeji.api"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hello.messeji.api.SleepSounds.getDescriptor(),
        }, assigner);
    internal_static_ReadReceipt_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReadReceipt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ReadReceipt_descriptor,
        new java.lang.String[] { "MessageIds", });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "SenderId", "Order", "MessageId", "Type", "SleepSoundsCommand", });
    internal_static_MultiMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_MultiMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MultiMessage_descriptor,
        new java.lang.String[] { "Messages", });
    com.hello.messeji.api.SleepSounds.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
